In [1]:
import pandas as pd

In [15]:
df = pd.read_csv("datasets/diabetes_unclean.csv")
df.head()

ID  No_Pation Gender   AGE  Urea    Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0  502      17975      F  50.0   4.7  46.0    4.9   4.2  0.9  2.4  1.4   0.5   
1  735      34221      M  26.0   4.5  62.0    4.9   3.7  1.4  1.1  2.1   0.6   
2  420      47975      F  50.0   4.7  46.0    4.9   4.2  0.9  2.4  1.4   0.5   
3  680      87656      F  50.0   4.7  46.0    4.9   4.2  0.9  2.4  1.4   0.5   
4  504      34223      M  33.0   7.1  46.0    4.9   4.9  1.0  0.8  2.0   0.4   

    BMI CLASS  
0  24.0     N  
1  23.0     N  
2  24.0     N  
3  24.0     N  
4  21.0     N

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1009 entries, 0 to 1008
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   ID         1009 non-null   int64  
 1   No_Pation  1009 non-null   int64  
 2   Gender     1009 non-null   object 
 3   AGE        1008 non-null   float64
 4   Urea       1008 non-null   float64
 5   Cr         1007 non-null   float64
 6   HbA1c      1006 non-null   float64
 7   Chol       1007 non-null   float64
 8   TG         1007 non-null   float64
 9   HDL        1008 non-null   float64
 10  LDL        1007 non-null   float64
 11  VLDL       1008 non-null   float64
 12  BMI        1009 non-null   float64
 13  CLASS      1009 non-null   object 
dtypes: float64(10), int64(2), object(2)
memory usage: 110.5+ KB


### Finding missing values 

In [17]:
df.isna().sum()

ID           0
No_Pation    0
Gender       0
AGE          1
Urea         1
Cr           2
HbA1c        3
Chol         2
TG           2
HDL          1
LDL          2
VLDL         1
BMI          0
CLASS        0
dtype: int64

In [22]:
import warnings 
warnings.filterwarnings('ignore')

In [26]:
mean_age = df['AGE'].mean()
df['AGE'].fillna(mean_age, inplace=True)

mean_Urea = df['Urea'].mean()
df['Urea'].fillna(mean_Urea, inplace=True)

mean_hbA1c = df['HbA1c'].mean()
df['HbA1c'].fillna(mean_hbA1c, inplace=True)

mean_chol = df['Chol'].mean()
df['Chol'].fillna(mean_chol, inplace=True)

mean_TG = df['TG'].mean()
df['TG'].fillna(mean_TG, inplace=True)

mean_HDL = df['HDL'].mean()
df['HDL'].fillna(mean_HDL, inplace=True)

mean_LDL = df['LDL'].mean()
df['LDL'].fillna(mean_LDL, inplace=True)

mean_VLDL = df['VLDL'].mean()
df['VLDL'].fillna(mean_VLDL, inplace=True)

mean_Cr = df['Cr'].mean()
df['Cr'].fillna(mean_Cr, inplace=True)

### Missing values filled

In [27]:
df.isnull().sum()

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

In [32]:
import numpy as np
import tensorflow as tf

In [40]:
x = df[['AGE']].values
y = df['Urea'].values
print(x)

[[50.]
 [26.]
 [50.]
 ...
 [62.]
 [57.]
 [55.]]


In [41]:
x_tensor = tf.constant(x, dtype=tf.float64)
y_tensor = tf.constant(y, dtype=tf.float64)

print(x_tensor)
print(y_tensor)

tf.Tensor(
[[50.]
 [26.]
 [50.]
 ...
 [62.]
 [57.]
 [55.]], shape=(1009, 1), dtype=float64)
tf.Tensor([4.7 4.5 4.7 ... 6.3 4.1 4.1], shape=(1009,), dtype=float64)
